NAME_FOLDER_ASTJDT = "merge_gtJDT_5_CDJDT_4"
NAME_FOLDER_ASTSPOON =  "merge_gt6_cd_5"
RESULTS_PROCESSED_LOCATION = "../../plots/data/"
RESULTS_ROW_LOCATION = "../../results/"
RESULTS_ROW_ASTJDT = "{}/{}".format(RESULTS_ROW_LOCATION, NAME_FOLDER_ASTJDT)
RESULTS_ROW_ASTSPOON = "{}/{}".format(RESULTS_ROW_LOCATION, NAME_FOLDER_ASTSPOON)